# -*- coding: utf-8 -*-
"""FYND_TASK1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K7g0gUld_5U2QvRB1vfJ92kPrswusMst
"""

###Setup and Dataset Loading

# ============================
#  TASK 1 — RATING PREDICTION
# ============================

# Install required libraries
!pip install kagglehub openai pandas tqdm

import kagglehub
import pandas as pd
import json
from tqdm import tqdm
import os

# ----------------------------
# Download Yelp Dataset
# ----------------------------

path = kagglehub.dataset_download("omkarsabnis/yelp-reviews-dataset")
print("Dataset downloaded to:", path)

# Check files
os.listdir(path)

# Identify filename (print previous cell output if unknown)
filename = "yelp.csv"

df = pd.read_csv(os.path.join(path, filename))
df = df[['text', 'stars']]

print(df.shape)
df.head()

# Sample 200 rows to speed up evaluation
sample = df.sample(200, random_state=42).reset_index(drop=True)
sample.head()

#api_key = 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

import requests
import json
import re

API_KEY = "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"
MODEL = "deepseek/deepseek-chat"

def call_llm(prompt):
    url = "https://openrouter.ai/api/v1/chat/completions"
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {API_KEY}",
    }

    payload = {
        "model": MODEL,
        "messages": [{"role": "user", "content": prompt}],
        "temperature": 0
    }

    response = requests.post(url, headers=headers, json=payload)
    data = response.json()

    if "choices" not in data:
        return "{}"

    content = data["choices"][0]["message"]["content"]

    # Extract JSON between { ... }
    match = re.search(r'\{.*\}', content, re.DOTALL)
    if match:
        return match.group(0)

    return "{}"

call_llm("Hello, test message")

def prompt_zero_shot(text):
    return f"""
You MUST return ONLY a valid JSON object.

STRICT RULES:
- No explanations outside JSON
- No extra text
- No emojis
- No comments
- Keys must be exactly: predicted_stars, explanation

OUTPUT FORMAT:
{{
  "predicted_stars": <number between 1 and 5>,
  "explanation": "<short sentence>"
}}

Review: "{text}"
Return ONLY the JSON object.
"""

def prompt_few_shot(text):
    return f"""
You are an expert Yelp review rater.

STRICT OUTPUT RULES:
- Return ONLY a JSON object.
- No text outside JSON.
- Keys: predicted_stars, explanation

Examples:

Review: "Terrible food, cold and overpriced."
Output: {{"predicted_stars": 1, "explanation": "Negative sentiment"}}

Review: "Decent place, nothing special."
Output: {{"predicted_stars": 3, "explanation": "Neutral experience"}}

Review: "Amazing service and delicious food!"
Output: {{"predicted_stars": 5, "explanation": "Strongly positive"}}

Now classify this review:
"{text}"

Return ONLY the JSON.
"""

def prompt_cot(text):
    return f"""
Evaluate the sentiment internally but DO NOT show reasoning.

STRICT OUTPUT RULES:
- Return ONLY JSON
- Keys: predicted_stars, explanation

OUTPUT FORMAT:
{{
  "predicted_stars": <1 to 5>,
  "explanation": "<short reason>"
}}

Review: "{text}"
Return ONLY the JSON.
"""

def evaluate_prompt(prompt_func, name):
    print(f"\nEvaluating: {name}")
    results = []

    for i, row in tqdm(sample.iterrows(), total=len(sample)):
        prompt = prompt_func(row['text'])
        raw_response = call_llm(prompt)

        # Try parsing JSON
        try:
            parsed = json.loads(raw_response)
            valid = True
            predicted = parsed.get("predicted_stars", None)
        except:
            valid = False
            predicted = None

        results.append({
            "actual": row['stars'],
            "predicted": predicted,
            "json_valid": valid
        })

    df_result = pd.DataFrame(results)
    df_result.to_csv(f"results_{name}.csv", index=False)

    accuracy = (df_result['actual'] == df_result['predicted']).mean()
    json_rate = df_result['json_valid'].mean()

    print(f"Accuracy: {accuracy:.3f}")
    print(f"JSON Validity: {json_rate:.3f}")

    return df_result, accuracy, json_rate

results['zero'], acc0, json0 = evaluate_prompt(prompt_zero_shot, "zero_shot")
results['few'], acc1, json1 = evaluate_prompt(prompt_few_shot, "few_shot")
results['cot'], acc2, json2 = evaluate_prompt(prompt_cot, "cot")

comparison = pd.DataFrame({
    "Prompt": ["Zero-Shot", "Few-Shot", "Chain-of-Thought"],
    "Accuracy": [acc0, acc1, acc2],
    "JSON Validity": [json0, json1, json2]
})

comparison

comparison.to_csv("prompt_comparison.csv", index=False)
comparison

